// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3Tcdr4ASaerO7h4o4_dVLF7VCA16Sdw',
    appId: '1:488111643065:android:f9c62091cf5691735f3e68',
    messagingSenderId: '488111643065',
    projectId: 'cenkoapp',
    storageBucket: 'cenkoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjIxZ0e7f6O6ypkyPjdUU0QpFfSuY7RE',
    appId: '1:488111643065:ios:25e8c6faa1daa5045f3e68',
    messagingSenderId: '488111643065',
    projectId: 'cenkoapp',
    storageBucket: 'cenkoapp.firebasestorage.app',
    androidClientId: '488111643065-4clks2lv6kqd9r069ntu01ucaaidhjil.apps.googleusercontent.com',
    iosClientId: '488111643065-pct09kignuneha47gf0gatuf16lt44m8.apps.googleusercontent.com',
    iosBundleId: 'com.lebaaar.cenko',
  );
}
