name: scraper

on:
  schedule:
    - cron: '0 6 * * *'  # 08:00 CEST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: ${{ matrix.store }}
    strategy:
      fail-fast: false
      matrix:
        store: [lidl, mercator, tusdrogerija, spar]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: scraper/requirements.txt

      - name: Install Python dependencies
        run: pip install -r scraper/requirements.txt

      - name: Scrape ${{ matrix.store }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py --store ${{ matrix.store }}
        working-directory: scraper
